run_storage:
  module: dagster_postgres.run_storage
  class: PostgresRunStorage
  config:
    postgres_db:
      username: postgres
      password:
        env: PGPASSWORD
      hostname: 127.0.0.1
      db_name: dagster
      port: 5432

event_log_storage:
  module: dagster_postgres.event_log
  class: PostgresEventLogStorage
  config:
    postgres_db:
      username: postgres
      password:
        env: PGPASSWORD
      hostname: 127.0.0.1
      db_name: dagster
      port: 5432

schedule_storage:
  module: dagster_postgres.schedule_storage
  class: PostgresScheduleStorage
  config:
    postgres_db:
      username: postgres
      password:
        env: PGPASSWORD
      hostname: 127.0.0.1
      db_name: dagster
      port: 5432